#!/bin/sh

# Extract the flag from the commit message
FLAG=$(git log -1 --pretty=%B | grep -o -- '--chaos')

# Pass the flag to the run-hooks.js script
if [ -n "$FLAG" ]; then
  node C:\Users\02cal\simple-react\node_modules\prepushpals\run-hooks.js --chaos
else
  node C:\Users\02cal\simple-react\node_modules\prepushpals\run-hooks.js
fi
